db:
    image: mongo
    ports:
        - "27017"
    volumes:
        - .:/app
    working_dir: /app
    command: bash -c "mongod & cd db && ./seed.sh && sleep infinity"
app:
    image: node
    links:
        - db:mongo
    ports:
        - "80:3000"
    volumes:
        - .:/home/node
    working_dir: /home/node
    command: node app